#!/bin/bash
#
# Voxplore (Voxplore) Docker Entrypoint Script
# AI-Powered Video Creation Desktop App
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Print welcome banner
echo "=============================================="
echo "  Voxplore (Voxplore)"
echo "  AI-Powered Video Creation Desktop App"
echo "=============================================="
echo ""

# Check environment
APP_MODE=${APP_MODE:-cpu}
log_info "Running in ${APP_MODE} mode"

# Check for required directories
REQUIRED_DIRS=("/app/logs" "/app/cache" "/app/output")
for dir in "${REQUIRED_DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        log_info "Creating directory: $dir"
        mkdir -p "$dir"
    fi
done

# Set Python path
export PYTHONPATH="/app:${PYTHONPATH}"
export APP_HOME=${APP_HOME:-/app}
export APP_CACHE=${APP_CACHE:-/app/cache}
export APP_OUTPUT=${APP_OUTPUT:-/app/output}

# Handle GPU detection
if [ "$APP_MODE" = "gpu" ]; then
    if command -v nvidia-smi &> /dev/null; then
        log_success "NVIDIA GPU detected"
        nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
    else
        log_warning "GPU mode requested but no NVIDIA GPU found"
    fi
fi

# Check for config files
CONFIG_DIR="/app/config"
if [ -d "$CONFIG_DIR" ]; then
    log_info "Config directory found at $CONFIG_DIR"
    # Copy default config if none exists
    if [ ! -f "$CONFIG_DIR/app.yaml" ] && [ -f "$CONFIG_DIR/app.example.yaml" ]; then
        log_info "Copying example config..."
        cp "$CONFIG_DIR/app.example.yaml" "$CONFIG_DIR/app.yaml"
    fi
fi

# Verify PySide6/Qt installation
log_info "Verifying Qt installation..."
python -c "from PySide6 import QtCore; print(f'  PySide6 version: {QtCore.qVersion()}')" || log_warning "PySide6 not properly installed"

# Check CUDA availability (if GPU mode)
if [ "$APP_MODE" = "gpu" ]; then
    log_info "Checking CUDA availability..."
    python -c "import torch; print(f'  CUDA available: {torch.cuda.is_available()}'); print(f'  CUDA device count: {torch.cuda.device_count() if torch.cuda.is_available() else 0}')" 2>/dev/null || log_warning "Could not verify CUDA"
fi

# Create .env file from environment if it doesn't exist
if [ ! -f "/app/.env" ]; then
    log_info "Creating .env file from environment variables..."
    cat > /app/.env << 'ENVEOF'
# Voxplore Environment Configuration
# Generated by docker_entrypoint.sh

APP_HOME=/app
APP_CACHE=/app/cache
APP_OUTPUT=/app/output
ENVEOF
fi

# Print startup info
echo ""
log_success "Voxplore is ready!"
echo ""
echo "  App Home:   $APP_HOME"
echo "  App Cache:  $APP_CACHE"
echo "  App Output: $APP_OUTPUT"
echo "  Mode:       $APP_MODE"
echo ""

# If running with display (GUI mode in container)
if [ -n "$DISPLAY" ]; then
    log_info "Display environment detected: $DISPLAY"
    # Allow X server connections from container
    xhost +local:docker 2>/dev/null || true
fi

# Execute the main command
log_info "Starting application..."
echo ""

# Pass control to the main application
exec "$@"
